name: Typst Tasks

on:
  push:
    branches: [ main ]
    paths:
      - '**.typ'
  pull_request:
    branches: [ main ]
    paths:
      - '**.typ'
  workflow_dispatch:

jobs:
  compile:
    name: Compiles the typst project into a PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v4
      - run: typst compile doc/main.typ paper.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf