name: Typst Tasks

on:
  push:
    branches: [main]
    paths:
      - "**.typ"
  pull_request:
    branches: [main]
    paths:
      - "**.typ"
  workflow_dispatch:

env:
  TYPLT_REV: "6ef57b4"

jobs:
  compile:
    name: Compiles the typst project into a PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v4
        with:
          typst-version: ^0.13.0
      - run: typst compile doc/main.typ paper.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf

  grammar:
    name: Checks the grammar with LanguageTool
    needs: compile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "25"

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: "3.9.11"

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-typst-languagetool-${{ env.TYPLT_REV }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-typst-languagetool-${{ env.TYPLT_REV }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install typst-languagetool package
        run: cargo install --git=https://github.com/antonWetzel/typst-languagetool --rev $TYPLT_REV cli --features=bundle

      - name: Run Grammar Check
        env:
          JAVA_TOOL_OPTIONS: "-Djdk.xml.totalEntitySizeLimit=0"
        run: |
          # Create wrapper script
          cat > grammar-check-wrapper.sh << 'EOF'
          #!/usr/bin/env bash
          GRAMMAR_CHECKER="typst-languagetool"
          OUTPUT_FILE="/tmp/grammar_check_output.txt"
          ERROR_PATTERN="(info|Failed to compile document)"

          # Run the grammar checker and capture its output
          $GRAMMAR_CHECKER "$@" --bundle | tee "$OUTPUT_FILE"

          # Check if the output contains any error indicators
          if grep -Ei "$ERROR_PATTERN" "$OUTPUT_FILE" > /dev/null; then
              echo "::error::Grammar issues found. Check the output above."
              exit 1
          else
              echo "::notice::No grammar issues detected."
              exit 0
          fi
          EOF
          chmod +x grammar-check-wrapper.sh

          # Use the wrapper script
          ./grammar-check-wrapper.sh check --main=doc/main.typ --options=doc/dictionary.json